stages:
  clean:
    cmd: uv run src/clean.py
    deps:
      - src/clean.py
      - data/raw_statcast_data.parquet
      - params.yaml
    outs:
      - data/clean_statcast_data.parquet
  featurize:
    cmd: uv run src/featurize.py
    deps:
      - src/featurize.py
      - data/clean_statcast_data.parquet
    outs:
      - data/featurized/
  train:
    cmd: uv run src/train.py
    deps:
      - src/train.py
      - data/featurized/
    outs:
      - models/
  evaluate:
    cmd: uv run src/evaluate.py
    deps:
      - src/evaluate.py
      - models/
    outs:
      - metrics/evaluation.json
metrics:
  - dvclive/metrics.json
plots:
  - dvclive/plots/metrics:
      x: step
