stages:
  clean:
    cmd: uv run src/clean.py
    deps:
      - src/clean.py
      - data/raw_statcast_data.parquet
    outs:
      - data/clean_statcast_data.parquet
  featurize:
    cmd: uv run src/featurize.py
    deps:
      - src/featurize.py
      - data/clean_statcast_data.parquet
    outs:
      - data/featurized/
