stages:
  clean:
    cmd: python3 src/clean.py
    deps:
    - data/raw/2015_2024_statcast.parquet
    - src/clean.py
    - params.yaml
    outs:
    - data/cleaned/2015_2024_statcast_clean.parquet
  featurize:
    cmd: python3 src/featurize.py
    deps:
    - data/cleaned/2015_2024_statcast_clean.parquet
    - src/featurize.py
    - src/utils/featurize_utils.py
    outs:
    - data/training/2015_2024_statcast_train.parquet
  train:
    cmd: python3 src/train.py
    deps:
    - data/training/2015_2024_statcast_train.parquet
    - src/utils/lstm_model.py
    - src/utils/train_utils.py
    - src/train.py
    outs:
    - data/evaluate/pitcher_data.pickle
  evaluate:
    cmd: python3 src/evaluate.py data/evaluate/pitcher_data.pickle
    deps:
    - data/evaluate/pitcher_data.pickle
    - src/evaluate.py
    outs:
    - data/outputs/
plots:
- data/outputs/performance_gain
- data/outputs/accuracy_plots
- data/outputs/loss_plots
- data/outputs/confusion_matrix
- dvclive/Rodón, Carlos_logs/plots/metrics:
    x: step
- dvclive/Manaea, Sean_logs/plots/metrics:
    x: step
metrics:
- dvclive/Rodón, Carlos_logs/metrics.json
- dvclive/Manaea, Sean_logs/metrics.json
