clean:
  input_data_path: data/raw/2015_2024_statcast_train.parquet
  num_pitchers: 5
  start_year: 2015
  min_pitches: 0
featurize:
  input_data_path: data/cleaned/2015_2024_statcast_clean.parquet
train:
  input_data_path: data/training/2015_2024_statcast_train.parquet
  dropout: 0.4
  patience: 5
  kernel_regularizer: 0.1
  batch_size: 128
  time_steps: 25
  train_split: .7
  epochs: 200
  lstm_units: 128
