clean:
  input_data_path: data/raw/2015_2024_statcast.parquet
  num_pitchers: 1000000
  start_year: 2024
  min_pitches: 3000
featurize:
  input_data_path: data/cleaned/2015_2024_statcast_clean.parquet
  features_path: data/full_features.txt
train:
  input_data_path: data/training/2015_2024_statcast_train.parquet
  features_path: data/full_features.txt
  dropout: .1
  patience: 4
