clean:
  input_data_path: data/raw/2015_2024_statcast.parquet
  num_pitchers: 50
  start_year: 2024
  min_pitches: 0
featurize:
  input_data_path: data/cleaned/2015_2024_statcast_clean.parquet
train:
  input_data_path: data/training/2015_2024_statcast_train.parquet
  features_path: data/full_features.txt
  dropout: 0.1 # keep this at 0.1
  patience: 10
  kernel_regularizer: 0.00 # keep this at 0.01
  batch_normalization: true
  batch_size: 32
  time_steps: 25
  train_split: .8
  epochs: 200
  lstm_units: 64
