clean:
  input_data_path: data/raw/2015_2024_statcast.parquet
  num_pitchers: 2
  start_year: 2015
  min_pitches: 0
featurize:
  input_data_path: data/cleaned/2015_2024_statcast_clean.parquet
train:
  input_data_path: data/training/2015_2024_statcast_train.parquet
  dropout: 0.2
  patience: 30
  kernel_regularizer: 0.001
  batch_normalization: True
  batch_size: 64
  time_steps: 25
  train_split: .8
  epochs: 200
  lstm_units: 256
