clean:
  input_data_path: data/raw/2015_2024_statcast.parquet
  num_pitchers: 3
  start_year: 2019
  min_pitches: 0
featurize:
  input_data_path: data/cleaned/2015_2024_statcast_clean.parquet
train:
  input_data_path: data/training/2015_2024_statcast_train.parquet
  features_path: data/full_features.txt
  dropout: 0.1
  patience: 10
  kernel_regularizer: 0.1
  batch_normalization: True
  batch_size: 64
  time_steps: 10
  train_split: .8
  epochs: 100
  lstm_units: 8
